### ISSUE TITLE
Common AWS SQL Datasources

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana-aws-sdk#28]
See design document at: https://docs.google.com/document/d/1V3SJGER5zIEQ_x-jHTE3gUIOvDMYqeYFsG4jxtTdux4/edit#

The objective of the refactoring is to reduce the amount of time spent on maintaining and developing new and existing SQL data sources for AWS, having a bigger source of common code.

Chores:
- [x] https://github.com/grafana/grafana-aws-sdk/issues/27 
- [x] https://github.com/grafana/grafana-aws-sdk/issues/26 

Backend
- [x] Create an API package with a common interface
- [x] Create a Driver package with a basic interface
- [x] Create a “routes” package with common routes
- [x] Create a datasource package for handling connections
- [x] Expose method to set the User-Agent header https://github.com/grafana/grafana-aws-sdk/pull/36

Frontend
- [x] ResourceSelector component
- [x] ConfigEditor component
- [x] QueryCodeEditor component
- [x] QueryEditor component (with support for examples)
- [x] Suggestions utils
~~- [ ] VariableSupport class~~
- [x] Datasource class

Athena
- [x] Migrate plugin to use the common packages

Redshift
- [x] Migrate plugin to use the common packages

Timestream
~~- [ ] Migrate plugin to use sqlds (requires a golang SQL driver)~~
~~- [ ] Migrate plugin to use the common packages~~

**Comment by andresmgot** [comment]
Created a different issue/epic for Timestream: https://github.com/grafana/timestream-datasource/issues/124 

So we can consider this done.
